# -*- coding: utf-8 -*-
"""YourWebProfile_Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LHhIS1S4eXNowtmPt6wUBZ9UNtm4Ma50
"""

#If the package is not already installed on your Colab, use the following command (without #):
#!pip install plotly

!pip install plotly
import plotly.graph_objs as go
import plotly.offline as pyo

def main():
    fig = go.Figure()

    fig.add_trace(go.Scatter(x=[1, 2], y=[3, 4], mode='lines', name='Line Chart'))

    fig.update_layout(
        title="My Profile",
        xaxis_title="X-Axis",
        yaxis_title="Y-Axis",
        showlegend=True,
        template="plotly",
    )

    # Convert the figure to HTML
    plot_div = pyo.plot(fig, output_type='div', include_plotlyjs=False)

    video_embed = """
    <iframe width="480" height="270" src="https://www.youtube.com/embed/-pfxn8h03M0" frameborder="0" allowfullscreen></iframe>
    """

    admission_image = "thomas-lipke-EIlFju7QOds-unsplash.jpg"

    skills = "Advanced Financial Analysis - Machine Learning - KPIs and Best Estimates - Extra Financial Performance Statements - Data Analytics - Python - Refinitiv Codebook... <strong>and more! Contact me.</strong>"

    content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title> My Profile -Python Generated </title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
            }}
            h1, h2 {{
                color: #1f6ca6;
            }}
            p {{
                color: #333;
                word-wrap: break-word;
            }}
            a {{
                color: #1f6ca6;
                text-decoration: none;
            }}
        </style>
        <!-- Add Plotly.js -->
        {plot_div}
    </head>
    <body>
        <h1> Grad on a Job Hunt </h1>
        <p>Hello everyone! I am an enthusiastic student pursuing a Master's degree in Audit and Expertise. My education at <a href="https://www.essca.fr/en/" target="_blank">ESSCA Business School</a> has provided me with a strong foundation in audit and financial expertise. As part of my studies, I have had the opportunity to delve into a topic of significance that is a hallmark of prominent audit firms.</p>

        <h2>Focus: Integrating AI into Auditing</h2>
        <img src="{admission_image}" alt="Admission Image" style="max-width: 200px; height: auto;">

        <p>My work focuses on <strong>integrating artificial intelligence into the audit process</strong>. I am particularly interested in how AI can enhance the efficiency and accuracy of financial auditing by automating repetitive tasks and identifying anomalies.</p>

        <h2>Discover My School</h2>
        {video_embed}
        <p><strong>Skills:</strong> {skills}</p>

    </body>
    </html>
    """

    # Write the content to an HTML file
    with open("exemple.html", "w", encoding="utf-8") as file:
        file.write(content)

if __name__ == "__main__":
    main()

